### ISSUE TITLE
Camel case

### ISSUE THREAD

**Issue by flo-we** [codemodus/kace#1]
Transformation to lower camel case does not work if your first character is upper case.

e. g. Camel("NotAwesome",false) returns "NotAwesome" instead of "notAwesome".

**Comment by daved** [comment]
Thanks for reporting this.  I'm taking a look now.

*I believe that I had set this behavior intentionally ([as shown in this test](https://github.com/codemodus/kace/blob/2689bf6b416ad7b76581174b6a7ce2214c75ff01/kace_test.go#L48)).  The function is a filter such that "true" would force the first character to be upper case, but false would simply not run that filter and leave the first character whatever it was before.

**Comment by daved** [comment]
The behavior you're suggesting does seem more reasonable to me.

**Comment by daved** [comment]
Fixed by https://github.com/codemodus/kace/commit/0a773928521401fcc9783008d4f0f481dcc8601c
