### ISSUE TITLE
User-defined initialisms.

### ISSUE THREAD

**Issue by daved** [codemodus/kace#3]
From @natefinch in #2 
> I'd also like to have any functions that need to use the intiialisms list to have an alternate form that takes a customized list.

**Comment by daved** [comment]
This is a great idea.  I believe that it makes most sense to provide a "kace" type that can hold the mutable state.  The package level functions can remain for simple use, the most common for myself being for sql table names.

Any thoughts? @natefinch

**Comment by natefinch** [comment]
Yeah, I like that.  Keeps the API smaller, and allows for more customizations inside the type if that becomes pertinent (which seems likely).

Looking at the way it's done in net/http's client, might be as simple as 
```go
type Converter struct {
    Initialisms map[string]bool
}
```
With Snake, Camel, etc methods off of kace.Converter.

Then if we later wanted to add another customization, it's just another field on the converter.

**Comment by daved** [comment]
Sounds right.  Would `type Kace struct {...}` be OK?

**Comment by natefinch** [comment]
but then you'd initialize it as kace.Kace{}   that's why I was thinking
kace.Converter or some such.

**Comment by daved** [comment]
I see you're rationale. For initializing types that are named after a package, I typically use `New({args...})`.  Is that convention incorrect/uncommon?

**Comment by daved** [comment]
I realize that the comparison is a little indirect, but https://golang.org/pkg/errors does this.

**Comment by natefinch** [comment]
Yeah, new could work, since there's unlikely to be any more top level types in this package.

**Comment by natefinch** [comment]
On second thought.... it still has to return some value, which means a top level type.  So I'm not sure it's actually worth it unless there's some processing that needs to be done at initialization time.

**Comment by daved** [comment]
There is.  The custom map needs to be filtered to ensure all keys are fully upper, and no empty string keys exist.  I just finished this.  Please have a look: 9ff84503d3e7c681d1045aff168bbc3ed4789b0f

**Comment by daved** [comment]
BTW, the readme, tests, example, and docs are updated, so that ([browse files](https://github.com/codemodus/kace/tree/9ff84503d3e7c681d1045aff168bbc3ed4789b0f)) might be a starting point to review.

**Comment by daved** [comment]
Closed by 9ff84503d3e7c681d1045aff168bbc3ed4789b0f

**Comment by natefinch** [comment]
Awesome. Looks great, thanks!
