### ISSUE TITLE
snake->camel/pascal misuses initialisms

### ISSUE THREAD

**Issue by natefinch** [codemodus/kace#5]
for example:

foo_identifier gets turned into FooIDentifier instead of FooIdentifier

I tried to look at the code to propose a fix but I honestly can't follow what it's doing.

**Comment by daved** [comment]
I'll add the test case and fix it in a bit.

**Comment by daved** [comment]
Fixed by 5014436b6047e869bffac20eecddbbe55a0c050d

**Comment by natefinch** [comment]
Yay!  I'm surprised the change was so complicated, but it does make me feel better about not being able to figure it out myself :)
